---
# Exclude test files from linting
exclude:
  - "**/*_test.go"

linters-settings:
  govet:
    shadow: false

  gocyclo:
    min-complexity: 20

  typecheck:
    skip-dirs:
      - "**/*.go"

  revive:
    disable:
      - var-naming


