server:
  api:
    name: "api"
    version: "v1"
  host: "127.0.0.1"
  port: 8090

database:
  uri: "mongodb://localhost:27017"
  name: "lead-stream-service-test"
  collection:
    schemas: "schemas"
    leads: "leads"