# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Set environment variable
      run: echo "ENVIRONMENT=TEST" >> "$GITHUB_ENV"

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: go build -v ./cmd/main.go

    - name: Test
      run: chmod +x ./cmd/run_tests.sh && ./cmd/run_tests.sh

    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
        name: Go-results
        path: test_results.json

  run-lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}